# Generated by Django 5.2.8 on 2025-11-26 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('CONSUMIVEL', 'Consumíveis'), ('MEDICAMENTO', 'Medicamentos'), ('EPI', 'EPI'), ('INSTRUMENTAL', 'Instrumental')], max_length=50)),
                ('unidade_medida', models.CharField(choices=[('UNIDADE', 'Unidade'), ('CAIXA', 'Caixa'), ('FRASCO', 'Frasco'), ('KIT', 'Kit'), ('PACOTE', 'Pacote'), ('LITRO', 'Litro'), ('PAR', 'Par'), ('ROLO', 'Rolo')], max_length=20)),
                ('estoque_minimo', models.IntegerField(default=5)),
                ('saldo_geral', models.IntegerField(default=0)),
                ('custo_medio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50)),
                ('data_validade', models.DateField()),
                ('quantidade_lote', models.IntegerField(default=0)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='insumos.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Compra)'), ('SAIDA', 'Saída (Uso)')], max_length=10)),
                ('quantidade', models.IntegerField()),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motivo', models.CharField(blank=True, max_length=200, null=True)),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionario.funcionario')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.lote')),
            ],
        ),
    ]
