# Generated by Django 5.2.8 on 2025-11-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('local_nascimento', models.CharField(max_length=100)),
                ('fone', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('cargo', models.CharField(max_length=50)),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Administrador'), ('PADRAO', 'Padrão')], default='PADRAO', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
